name: Maven Package

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

#    - name: Build with Maven
#      run: mvn clean  install -pl mybatis-hotswap-springboot-starter  -am

#    - name: Publish to GitHub Packages Apache Maven
#      run: mvn clean deploy -pl mybatis-hotswap-springboot-starter  -am  -s $GITHUB_WORKSPACE/settings.xml
#      env:
#        GITHUB_TOKEN: ${{ github.token }}
#        MAVEN_USERNAME: MAVEN_USERNAME
#        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
#        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}


    - name: Set up Apache Maven Central
      uses: actions/setup-java@v2
      with: # running setup-java again overwrites the settings.xml
        distribution: 'temurin'
        java-version: '11'
        server-id: sonatype-staging # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: ${{ secrets.MAVEN_USERNAME }} # env variable for username in deploy
        server-password: ${{ secrets.MAVEN_CENTRAL_TOKEN }} # env variable for token in deploy
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
        gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }} # env variable for GPG private key passphrase

    - name: Publish to Apache Maven Central
      run: mvn clean deploy -B -pl mybatis-hotswap-springboot-starter  -am
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
